- name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-frontend
          IMAGE_TAG: latest
        run: |
          DOCKERFILE_PATH=$(find . -maxdepth 1 -iname "dockerfile" | head -n 1)
          if [ -z "$DOCKERFILE_PATH" ]; then
            echo "ERROR: no se encontró Dockerfile en la raíz"
            ls -la
            exit 1
          fi
          echo "Usando Dockerfile: $DOCKERFILE_PATH"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f "$DOCKERFILE_PATH" .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
